import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { ArrowRight, BarChart3, BriefcaseBusiness, Check, ChevronRight, Code2, Filter, MapPin, Sparkles, Target, X } from "lucide-react";
import { AddSkillButton, AppShell, DemoBadge, DemoBanner, LevelBars, MiniStat, PageGuard, RoleIdentity, SearchResource, SectionHeading, SkillChip } from "@/components/career/CareerUI";
import { getRole, skills, type InternshipMatch } from "@/data/career";
import { useCareer } from "@/context/CareerContext";

function scoreTone(score: number) {
  if (score >= 75) return "text-success";
  if (score >= 50) return "text-warning";
  return "text-muted-foreground";
}

export default function Dashboard() {
  const [, setLocation] = useLocation();
  const { readiness, matches, gaps, skills: skillEntries, profile, roadmap, role, generateRoadmap, startInterview } = useCareer();
  const [tab, setTab] = useState<"internships" | "gaps">("internships");
  const [onlyRole, setOnlyRole] = useState(false);
  const [mode, setMode] = useState("all");
  const [selected, setSelected] = useState<InternshipMatch | null>(null);

  const roadmapProgress = useMemo(() => {
    const tasks = roadmap?.flatMap((day) => day.tasks) ?? [];
    return tasks.length ? Math.round((tasks.filter((task) => task.completed).length / tasks.length) * 100) : 0;
  }, [roadmap]);
  const filtered = useMemo(() => matches.filter((match) => (!onlyRole || match.role === role) && (mode === "all" || match.workMode === mode)), [matches, mode, onlyRole, role]);
  const topMatch = matches[0]?.score ?? 0;
  const hasRoadmap = Boolean(roadmap);

  const next = hasRoadmap
    ? roadmapProgress < 100
      ? { label: `Roadmap-ı davam et (${roadmapProgress}%)`, description: "Yarımçıq qalan task-larınızı tamamlayın.", action: () => setLocation("/roadmap") }
      : { label: "Mock müsahibəyə başla", description: "Nə öyrəndiyinizi 5 sualda yoxlayın.", action: () => { startInterview(); setLocation("/interview"); } }
    : { label: "7 günlük roadmap yarat", description: `${gaps.length} prioritet skill gap-i üçün plan hazırlayın.`, action: () => { generateRoadmap(); setLocation("/roadmap"); } };

  return <PageGuard><AppShell><DemoBanner />
    <SectionHeading eyebrow="İcmal" title={`Salam, ${profile.name}`} description={`${getRole(role).name} istiqamətində vəziyyətiniz və növbəti prioritetləriniz.`} action={<RoleIdentity />} />
    <section className="mb-7 rounded-2xl border border-primary/25 bg-[linear-gradient(115deg,rgba(47,93,255,0.16),rgba(17,17,19,0.2)_42%)] p-5 sm:p-6">
      <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><div className="mb-2 flex items-center gap-2 text-xs font-medium text-accent"><Sparkles className="size-3.5" /> NÖVBƏTİ ƏMƏLİYYAT</div><h2 className="text-xl font-semibold tracking-[-0.04em]">{next.label}</h2><p className="mt-1 text-sm text-secondary-foreground">{next.description}</p></div><button type="button" onClick={next.action} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-medium text-white transition hover:bg-[#4672ff]">Davam et <ArrowRight className="size-4" /></button></div>
    </section>
    <section className="mb-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MiniStat icon={Target} label="Role Readiness" value={`${readiness}%`} hint="Hədəf rol üçün təxmini" tone={readiness >= 70 ? "green" : "blue"} /><MiniStat icon={BriefcaseBusiness} label="Ən yaxşı uyğunluq" value={`${topMatch}%`} hint="12 demo elan içindən" tone={topMatch >= 75 ? "green" : "amber"} /><MiniStat icon={Code2} label="Aşkarlanan bacarıq" value={skillEntries.length} hint="CV və əl ilə əlavə edilən" /><MiniStat icon={BarChart3} label="Roadmap progress" value={`${roadmapProgress}%`} hint={hasRoadmap ? "Plan üzrə irəliləyiş" : "Plan hələ yaradılmayıb"} tone={roadmapProgress === 100 ? "green" : "blue"} /></section>
    <section className="grid gap-6 lg:grid-cols-[320px_minmax(0,1fr)]">
      <aside className="rounded-2xl border border-border bg-card p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">Profil</p><h2 className="mt-1 font-semibold">{profile.candidateLevel}</h2></div><DemoBadge /></div><p className="text-sm leading-6 text-secondary-foreground">{profile.summary}</p><div className="my-5 h-px bg-border" /><p className="mb-3 text-xs font-medium text-muted-foreground">Bacarıqlar · kliklə səviyyəni dəyiş</p><div className="flex flex-wrap gap-2">{skillEntries.map((skill) => <SkillChip key={skill.slug} skill={skill} />)}<AddSkillButton /></div><div className="my-5 h-px bg-border" /><p className="mb-3 text-xs font-medium text-muted-foreground">Seçilmiş təcrübə</p><ul className="space-y-3">{profile.highlights.map((item) => <li key={item} className="flex gap-2 text-xs leading-5 text-muted-foreground"><Check className="mt-0.5 size-3.5 shrink-0 text-success" />{item}</li>)}</ul></aside>
      <div className="min-w-0"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="inline-flex rounded-xl border border-border bg-secondary p-1"><button type="button" onClick={() => setTab("internships")} className={`rounded-lg px-3 py-2 text-sm ${tab === "internships" ? "bg-card text-foreground shadow-sm" : "text-muted-foreground"}`}>Internship-lər <span className="ml-1 text-xs">{matches.length}</span></button><button type="button" onClick={() => setTab("gaps")} className={`rounded-lg px-3 py-2 text-sm ${tab === "gaps" ? "bg-card text-foreground shadow-sm" : "text-muted-foreground"}`}>Skill gap-lər <span className="ml-1 text-xs">{gaps.length}</span></button></div>{tab === "internships" && <div className="flex items-center gap-2"><button type="button" onClick={() => setOnlyRole((value) => !value)} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs ${onlyRole ? "border-primary/50 bg-primary/10 text-accent" : "border-border text-muted-foreground"}`}><Filter className="size-3.5" />Yalnız rol</button><select value={mode} onChange={(event) => setMode(event.target.value)} className="rounded-lg border border-border bg-secondary px-2.5 py-2 text-xs text-secondary-foreground outline-none"><option value="all">Bütün rejimlər</option><option value="Remote">Remote</option><option value="Hibrid">Hibrid</option><option value="Ofis">Ofis</option></select></div>}</div>
        {tab === "internships" ? <div className="space-y-3">{filtered.map((match) => <InternshipCard key={match.id} match={match} onOpen={() => setSelected(match)} />)}{filtered.length === 0 && <div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Bu filtrlə nəticə yoxdur. Filtri sıfırlayın.</div>}</div> : <div className="space-y-3">{gaps.map((gap) => <div key={gap.slug} className="flex flex-col gap-4 rounded-xl border border-border bg-card p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="font-medium">{gap.name}</h3><span className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${gap.priority === "high" ? "bg-warning/15 text-warning" : gap.priority === "medium" ? "bg-info/15 text-info" : "bg-secondary text-muted-foreground"}`}>{gap.priority === "high" ? "Yüksək prioritet" : gap.priority === "medium" ? "Orta prioritet" : "Aşağı prioritet"}</span></div><div className="mt-3 flex flex-wrap items-center gap-3"><LevelBars current={gap.currentLevel} required={gap.requiredLevel} /><span className="text-xs text-muted-foreground">{gap.currentLevel}/{gap.requiredLevel} · fərq {gap.gap}</span></div></div><button type="button" onClick={() => { generateRoadmap(); setLocation("/roadmap"); }} className="inline-flex shrink-0 items-center gap-1.5 rounded-lg bg-secondary px-3 py-2 text-xs text-secondary-foreground hover:bg-muted">{hasRoadmap ? "Planda göstər" : "Öyrənmə planı yarat"}<ChevronRight className="size-3.5" /></button></div>)}{gaps.length === 0 && <div className="rounded-xl border border-border bg-card p-8 text-center text-sm text-muted-foreground">Hədəf rol üçün çatışmayan bacarıq yoxdur.</div>}</div>}
      </div>
    </section>
    {selected && <InternshipDetail match={selected} onClose={() => setSelected(null)} />}
  </AppShell></PageGuard>;
}

function InternshipCard({ match, onOpen }: { match: InternshipMatch; onOpen: () => void }) {
  return <button type="button" onClick={onOpen} className="group w-full rounded-xl border border-border bg-card p-4 text-left transition hover:border-accent/50 focus-visible:ring-2 focus-visible:ring-ring sm:p-5"><div className="flex gap-4"><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><DemoBadge /><span className="rounded-full bg-secondary px-2 py-1 text-[11px] text-muted-foreground">{match.workMode}</span></div><h3 className="truncate text-base font-semibold">{match.title}</h3><p className="mt-1 text-sm text-secondary-foreground">{match.company} · {match.location}</p></div><div className="text-right"><p className="text-[11px] text-muted-foreground">Uyğunluq</p><p className={`mt-1 text-3xl font-semibold tracking-[-0.06em] tabular-nums ${scoreTone(match.score)}`}>{match.score}%</p></div></div><div className="mt-4 grid gap-3 border-t border-border pt-3 sm:grid-cols-2"><div><p className="mb-1.5 text-[11px] text-muted-foreground">Uyğun bacarıqlar</p><div className="flex flex-wrap gap-1.5">{match.matched.slice(0,4).map((slug) => <span key={slug} className="inline-flex items-center gap-1 rounded bg-success/10 px-2 py-1 text-[11px] text-success"><Check className="size-3" />{skills[slug].name}</span>)}{match.matched.length === 0 && <span className="text-xs text-muted-foreground">Hələ uyğun skill yoxdur</span>}</div></div><div><p className="mb-1.5 text-[11px] text-muted-foreground">Çatışmayanlar</p><div className="flex flex-wrap gap-1.5">{match.missing.slice(0,4).map((slug) => <span key={slug} className="rounded bg-secondary px-2 py-1 text-[11px] text-muted-foreground">{skills[slug].name}</span>)}{match.missing.length === 0 && <span className="text-xs text-success">Əsas tələblər qarşılanır</span>}</div></div></div></button>;
}

function InternshipDetail({ match, onClose }: { match: InternshipMatch; onClose: () => void }) {
  const { role } = useCareer();
  return <div className="fixed inset-0 z-50 flex justify-end" role="dialog" aria-modal="true" aria-label="Internship detalları"><button type="button" onClick={onClose} className="absolute inset-0 bg-black/60" aria-label="Detail panelini bağla" /><aside className="relative h-full w-full max-w-md overflow-y-auto border-l border-border bg-background p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="mb-3 flex items-center gap-2"><DemoBadge /><span className="rounded-full bg-secondary px-2 py-1 text-[11px] text-muted-foreground">{match.workMode}</span></div><h2 className="text-2xl font-semibold tracking-[-0.05em]">{match.title}</h2><p className="mt-2 text-sm text-secondary-foreground">{match.company} · {match.location}</p></div><button type="button" onClick={onClose} className="grid size-9 place-items-center rounded-lg bg-secondary text-muted-foreground"><X className="size-4" /></button></div><div className="my-7 rounded-2xl border border-border bg-card p-5"><p className="text-xs text-muted-foreground">Təxmini uyğunluq</p><p className={`mt-1 text-5xl font-semibold tracking-[-0.07em] ${scoreTone(match.score)}`}>{match.score}%</p><p className="mt-3 text-xs leading-5 text-muted-foreground">Score bacarıqların səviyyəsi, required/preferred tələblər və hədəf rol bonusu ilə deterministik hesablanır.</p></div><div className="space-y-6"><div><h3 className="mb-2 font-medium">Rol haqqında</h3><p className="text-sm leading-6 text-secondary-foreground">{match.description}</p></div><div><h3 className="mb-3 font-medium">Tələb olunan bacarıqlar</h3><div className="space-y-2">{match.required.map((slug) => <div key={slug} className="flex items-center justify-between rounded-xl border border-border bg-card px-3 py-3"><span className="text-sm">{skills[slug].name}</span><span className="text-xs text-muted-foreground">{match.matched.includes(slug) ? "Profilinizdə var" : "İnkişaf etdirin"}</span></div>)}</div></div><div><h3 className="mb-3 font-medium">Uyğunluq qeydi</h3><p className="text-sm leading-6 text-muted-foreground">{match.role === role ? "Bu elan seçdiyiniz hədəf rolla eynidir və score-a 10% rol bonusu daxildir." : "Bu elan başqa rol ailəsinə aiddir; score yalnız bacarıq uyğunluğuna görə formalaşır."}</p></div><SearchResource query={`${match.title} beginner roadmap`} /></div></aside></div>;
}
